### PR TITLE
fix(settings): respect existing value for "fileNesting.expand" if present

### LINKED ISSUE #73: [Extension] Respect existing choice for "fileNesting.expand" or make it a setting to respect it
First of all, thank you very much for the extension, the idea, and all of your work generally in the JS ecosystem!

In https://github.com/antfu/vscode-file-nesting-config/commit/11f3dc5e427452f987352fae93fc9ab9e7e25ecb the code which checked for the presence of an existing settings for `explorer.experimental.fileNesting.expand` was removed in favor of _always_ setting it to `false`.

I may be in the minority given the reason this extension exists in the first place, but I actually prefer to see all of the files by default (i.e. `explorer.experimental.fileNesting.expand=true`) with the ability to collapse the nesting trees down if I feel overwhelmed.

An ideal outcome to me would be to make "_respect existing_ `explorer.experimental.fileNesting.expand` _selection_" an extension setting for `File Nesting Updater` so that the extension does not override how I have this nesting setting set (also, personally fine if my preference here is not the default, because as I said, I suspect I'm in the minority here).

Alternatively, one could argue that the extension just shouldn't touch this user setting - if a user has it set, or not, it's up to them. This leads to a solution which deletes code and introduces no added maintenance burden. Could also just note that this is a setting users might want to check on in the README and call that good?

For reference, here is a video demonstration of how invocation of the `File Nesting Updater` update command changes the value of `explorer.experimental.fileNesting.expand`:

https://user-images.githubusercontent.com/34140052/158517177-94e785e9-c750-4dd3-9cb2-9c48722f0dc3.mp4

### PR DESCRIPTION
**Pull request by andrewbrey**
Fixes #73

### CODE REVIEW

File: extension/src/fetch.ts [hunk 1]
```diff
@@ -38,7 +38,8 @@ export async function fetchAndUpdate(ctx: ExtensionContext, prompt = true) {
   if (shouldUpdate) {
     const config = workspace.getConfiguration()
     config.update('explorer.experimental.fileNesting.enabled', true, true)
-    config.update('explorer.experimental.fileNesting.expand', false, true)
+    config.update('explorer.experimental.fileNesting.expand',
+      config.inspect('explorer.experimental.fileNesting.expand').globalValue ?? false, true)
```
Comment (antfu) [inline extension/src/fetch.ts:42]: Maybe we could use a `if` so we don't touch it when the user set it explicitly?

Comment (andrewbrey) [reply extension/src/fetch.ts]: Sure, that is updated :+1:
